"""Generate a header that embeds doc/help.json as a DEFLATE stream.

Usage: compress-help.py <help_json> <output_header>

The JSON is minified exactly the way the uncompressed build does it - the same
`json.dump(..., separators=(",", ":"))` call that CMakeLists.txt used to run
inline - and then deflated. That takes the help text from roughly 23 KiB of
escaped C string literal down to roughly 5 KiB of bytes.

`helpJsonText()` in src/fastfetch.c inflates it back on demand. `--help` is a
cold path, so the few microseconds that costs do not matter.
"""

import json
import os
import sys
import zlib


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    source, output = sys.argv[1], sys.argv[2]

    with open(source, encoding="utf-8") as handle:
        minified = json.dumps(json.load(handle), separators=(",", ":"))

    # The embedded text is a C string, so anything non-ASCII would need escaping.
    # `json.dumps` defaults to ensure_ascii=True, which keeps it pure ASCII.
    if not minified.isascii():
        raise ValueError("the minified help text is not pure ASCII")

    raw = minified.encode("ascii")
    compressor = zlib.compressobj(9, zlib.DEFLATED, -15)
    payload = compressor.compress(raw) + compressor.flush()

    lines = [
        "// Generated by scripts/compress-help.py - do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define FASTFETCH_DATATEXT_JSON_HELP_SIZE {len(raw)}",
        f"#define FASTFETCH_DATATEXT_JSON_HELP_DEFLATE_SIZE {len(payload)}",
        "",
        "static const uint8_t ffHelpJsonCompressed[] = {",
    ]
    for start in range(0, len(payload), 16):
        chunk = payload[start:start + 16]
        lines.append("    " + ",".join("0x%02x" % byte for byte in chunk) + ",")
    lines += ["};", ""]

    tmp = output + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    os.replace(tmp, output)

    print(f"compress-help: {len(raw)} -> {len(payload)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
