"""Generate a header that embeds the built-in ascii logos as DEFLATE streams.

Usage: compress-logos.py <ascii_dir> <output_header>

Each logo becomes one self-contained block:

    [uint16 little-endian raw length][uint16 little-endian deflate length][raw DEFLATE stream]

Both lengths are stored in front of the stream so that no separate index table
is needed: `ffLogoDecompress()` reads them back and inflates into a fixed buffer.
The deflate length is what lets the decoder stop at the end of the stream instead
of trusting it, which matters because the same decoder also expands a `classes.dex`
read out of a jar on a device.
The macro for every logo points straight at its block inside one big array, so
the compiler folds the pointer arithmetic into a link-time constant.

This replaces the previous `file(GENERATE)` of one C string literal per logo
(see CMakeLists.txt), which stored the ascii art uncompressed.
"""

import os
import sys
import zlib


def block_for(raw: bytes) -> bytes:
    """raw DEFLATE (no zlib header/adler) with the two u16 lengths in front of it."""
    compressor = zlib.compressobj(9, zlib.DEFLATED, -15)
    payload = compressor.compress(raw) + compressor.flush()
    if len(raw) > 0xFFFF:
        raise ValueError(f"logo too large for a u16 length: {len(raw)}")
    return len(raw).to_bytes(2, "little") + len(payload).to_bytes(2, "little") + payload


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    ascii_dir, output = sys.argv[1], sys.argv[2]

    files = []
    for entry in sorted(os.listdir(ascii_dir)):
        sub = os.path.join(ascii_dir, entry)
        if not os.path.isdir(sub) or len(entry) != 1 or not (entry.islower() or entry == "_"):
            continue
        for name in sorted(os.listdir(sub)):
            if name.endswith(".txt"):
                files.append(os.path.join(sub, name))

    blob = bytearray()
    macros = []
    for path in files:
        with open(path, "rb") as handle:
            raw = handle.read()
        # CMakeLists' fastfetch_encode_c_string() strips exactly one trailing LF
        if raw.endswith(b"\n"):
            raw = raw[:-1]
        offset = len(blob)
        blob += block_for(raw)
        # get_filename_component(NAME_WE) drops the longest extension
        macro = os.path.splitext(os.path.basename(path))[0].split(".")[0].upper()
        macros.append((macro, offset))

    lines = [
        "// Generated by scripts/compress-logos.py - do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "static const uint8_t ffLogoCompressed[] = {",
    ]
    for start in range(0, len(blob), 16):
        chunk = blob[start:start + 16]
        lines.append("    " + ",".join("0x%02x" % byte for byte in chunk) + ",")
    lines += ["};", ""]
    for macro, offset in macros:
        lines.append(f"#define FASTFETCH_DATATEXT_LOGO_{macro} ((const char*) (ffLogoCompressed + {offset}))")
    lines.append("")

    tmp = output + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    os.replace(tmp, output)

    print(f"compress-logos: {len(files)} logos, {len(blob)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
